name: .NET BOT D1 INFRA AAILAB

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
  push:
    branches:
      - 'master'
    paths:
      - './Samples/PublicSamples/EchoBot/ADF/**'
      - .github/workflows/echobot-infra-AAILAB.yml

  pull_request:
    branches:
      - 'master'
    paths:
      - './Samples/PublicSamples/EchoBot/ADF/**'
      - .github/workflows/echobot-infra-AAILAB.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  OrgName: AAILAB
  Location: SoutheastAsia

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  EnvironmentDeploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_AAILAB_BOT}}
          enable-AzPSSession: true

      - name: Deploy_All_Subscription
        uses: Azure/powershell@v2
        with:
          azPSVersion: latest
          inlineScript: |
            $Params = @{
              OrgName         = $env:OrgName
              Location        = $env:location
              FullUpload      = $true
            }
            ./Samples/PublicSamples/EchoBot/ADF/main.ps1 @Params
            if ($e){throw $e}




